### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by itsmylife44** [Co2333/Iridium#1]
Hey buddy , 
i am trying to decrypt some app .
Currently on 14.6 checkra1n iphone 7

here is a screen .

![image](https://user-images.githubusercontent.com/34112129/148542782-f5a17eeb-cf2a-4378-aafb-bddff5fe1d16.png)
 maybe it can help you !

**Comment by Lakr233** [comment]
For this version, you are on your own to install `libkrw` from your package manager. I'll add them next time.

`libkrw` for uncover/checkra1n
`libkernrw` for taurine

**Comment by Lakr233** [comment]
<img width="229" alt="截屏2022-01-07 下午8 19 21" src="https://user-images.githubusercontent.com/25259084/148543193-6e4e734e-183b-40c9-8c45-afb41e2b7d3a.png">

**Comment by itsmylife44** [comment]
ok , i'll try it , thank you buddy :)

**Comment by itsmylife44** [comment]
looks good now . 
Thank You

**Comment by itsmylife44** [comment]
trying to siledload the decrypted app now on an  non jb device 

error : 
ERROR: Guru Meditation 0db732@811:3aea77 Failed: (7252) There is no 'ios' certificate with serial number 'xxxxxxxxxxxxxxxxxxxxxxxxxx' on this team.

don't know if is related to the decrypt or sideloadly

**Comment by Lakr233** [comment]
it's a problem on your side.

**Comment by Lakr233** [comment]
I have updated my app to embed the kernel interface in 1.1.0.
