### ISSUE TITLE
"arm64 dylibs cannot be loaded into arm64e processes"

### ISSUE THREAD

**Issue by mpelteshki** [Co2333/Iridium#4]
Running on an A12 device fails with error "arm64 dylibs cannot be loaded into arm64e processes"

**Comment by Lakr233** [comment]
Fixed Release 1.2.8

**Comment by Lakr233** [comment]
I haven't tested it yet because I'm having no device to do so. Let me know if it is crashing again or it fixed the problem.

**Comment by mpelteshki** [comment]
I'm still waiting for a friend to test it out (I don't have an arm64e device either :​/)
